"""Self-test for filter_diag (no real data):

    /usr/local/bin/python3 -m filter_diag.selftest

1. DSP model: cutoff/tau match the header formula, inverse round-trips.
2. Tail fit recovers a known tau; decomposition sanity.
3. End to end: synthetic RHS sessions whose artifacts are generated by the
   instrument model itself -- (a) pure rectangular step through the physical
   chain -> verdict must be FILTER-DOMINATED (tau ~ 136.5 ms, opposite-sign
   tails, recovery collapses under F1/F2); (b) step + slow same-sign input tail
   -> verdict must NOT be filter-dominated.
"""

from __future__ import annotations

import sys
import tempfile
import time
import traceback
from pathlib import Path

import numpy as np

from stim_analysis import selftest as st
from stim_analysis.config import AnalysisConfig
from filter_diag.common import ADC_FULL_SCALE_UV, dsp_k_from_cutoff, dsp_tau_s, fit_exponential_tail, intan_dsp_highpass, intan_dsp_inverse, verify_dsp_model
from filter_diag.synthetic_step import instrument_chain


class Check(st.Check):
    pass


def check_units(c: Check) -> None:
    v = verify_dsp_model(30000.0, 12)
    c.ok(abs(v["cutoff_hz"] - 1.165828) < 1e-5, f"DSP cutoff for k=12 at 30 kHz = {v['cutoff_hz']:.6f} Hz (header says 1.165828)")
    c.ok(abs(v["tau_ms_step_fit"] - v["tau_ms_expected"]) < 0.01 and abs(v["tau_ms_expected"] - 136.52) < 0.05, f"DSP step response tau = {v['tau_ms_step_fit']:.2f} ms (2^12/fs = 136.53)")
    c.ok(v["inverse_max_abs_error_uV"] < 1e-6, f"inverse DSP round-trips (max error {v['inverse_max_abs_error_uV']:.1e} uV)")
    c.ok(dsp_k_from_cutoff(30000.0, 1.1658) == 12 and dsp_k_from_cutoff(20000.0, 1.2) == 11, "k from cutoff: 12 at 30 kHz, 11 at 20 kHz")
    fs = 30000.0
    t_ms = (np.arange(int(1.5 * fs)) - int(0.6 * fs)) * 1e3 / fs
    rng = np.random.default_rng(0)
    for tau in (50.0, 136.5, 400.0):
        sig = np.where(t_ms > 0, -3000 * np.exp(-t_ms / tau), 0.0) + rng.normal(0, 15, t_ms.size)
        fit = fit_exponential_tail(sig, t_ms, exit_ms=0.0, excursion_sign=-1.0)
        c.ok(abs(fit.tau_ms / tau - 1) < 0.05 and fit.r2 > 0.95 and fit.tail_sign > 0, f"tail fit recovers tau {tau:g} ms -> {fit.tau_ms:.1f} ms (R2 {fit.r2:.3f}, same-sign)")
    # a brief rail-level pulse through the DSP leaves an opposite-sign overshoot
    x = np.zeros(int(2 * fs)); x[int(0.5 * fs):int(0.51 * fs)] = -ADC_FULL_SCALE_UV
    y = intan_dsp_highpass(x, fs, k=12, initial_mean=0.0)
    after = y[int(0.515 * fs):int(0.53 * fs)].mean()
    c.ok(after > 300, f"DSP overshoot after a 10 ms rail-level negative pulse is positive ({after:.0f} uV): opposite-sign signature")
    big = np.zeros(int(2 * fs)); big[int(0.5 * fs):int(0.51 * fs)] = -20000.0  # well beyond the ADC rail
    stages = instrument_chain(big, fs, k=12, rail_mode="freeze")
    rail = stages["recorded"][int(0.501 * fs):int(0.509 * fs)]
    c.ok(np.allclose(rail, -ADC_FULL_SCALE_UV, atol=1e-6), "freeze mode: recorded rail is flat at the extreme value for the whole saturated stretch")
    y_track = instrument_chain(big, fs, k=12, rail_mode="track")["recorded"][int(0.501 * fs):int(0.509 * fs)]
    c.ok(y_track[-1] > -ADC_FULL_SCALE_UV + 100, f"track mode: output lifts off the rail during saturation ({y_track[-1]:.0f} uV after 8 ms)")
    from filter_diag.common import intan_dsp_highpass_freeze
    clipped = np.clip(big, -ADC_FULL_SCALE_UV, ADC_FULL_SCALE_UV)
    fr = intan_dsp_highpass_freeze(clipped, fs, k=12, initial_mean=0.0)
    inv = intan_dsp_inverse(fr, fs, k=12, initial_mean=0.0, freeze_at_full_scale=True)
    c.ok(np.max(np.abs(inv - clipped)) < 1e-6, f"freeze-aware inverse round-trips the freeze forward model (max err {np.max(np.abs(inv - clipped)):.1e} uV)")


def _make_session(parent: Path, session: str, rng: np.random.Generator, *, tail: bool, k: int = 12) -> None:
    """3 single-pulse runs (20/50/100 uA) + a no-stim run, 4 channels; artifact = instrument model output."""
    fs = 30000.0
    names = ["A-024", "A-025", "A-026", "A-027"]
    n = 128 * 6000
    onsets = 30000 + np.arange(20) * 30001
    t = np.arange(n) / fs
    parent.mkdir(parents=True, exist_ok=True)

    def make_run(folder_name: str, amplitude: float, n_pulses: int) -> None:
        folder = parent / folder_name
        folder.mkdir()
        analog = rng.normal(0, 15, size=(4, n))
        words = np.zeros((4, n), dtype=np.uint16)
        if n_pulses:
            words[3] = st.biphasic_words(n, fs, onsets[:n_pulses], amplitude_uA=amplitude, phase_us=200)
            for onset in onsets[:n_pulses]:
                for ch in range(4):
                    gain = (0.5 + 0.25 * ch) * amplitude / 20.0
                    d = int(round((2.0 + 0.1 * amplitude) * 1e-3 * fs))  # rail duration grows with current
                    seg = slice(int(onset), min(n, int(onset) + d))
                    analog[ch, seg] += -20000.0 * gain
                    if tail:
                        tail_seg = slice(min(n, int(onset) + d), min(n, int(onset) + int(0.9 * fs)))
                        tt = t[tail_seg] - t[min(n - 1, int(onset) + d)]
                        analog[ch, tail_seg] += -2500.0 * gain * np.exp(-tt / 0.12)
        recorded = np.empty_like(analog)
        for ch in range(4):
            recorded[ch] = instrument_chain(analog[ch], fs, k=k, rail_mode="freeze")["recorded"]
        st.write_synthetic_rhs(folder / f"{folder_name.split(' ')[0]}.rhs", sample_rate_hz=fs, channel_names=names, amp_codes=st.uv_to_code(recorded), stim_words=words, impedances_ohms=[29e3, 240e3, 164e3, 88e3])
        (folder / "settings.xml").write_text(st._settings_xml("A-027", amplitude, 200, n_pulses, fs))

    make_run(f"recording_2601{'01' if session == 'live' else '02'}_100000", 0, 0)
    for i, amp in enumerate((20.0, 50.0, 100.0)):
        make_run(f"step1_2601{'01' if session == 'live' else '02'}_1001{i:02d} A-027 stim cathodic first 200us {amp:g}uA 1Hz 20 pulses 999ms RP", amp, 20)


def _patch_header_dsp(parent: Path) -> None:
    """The synthetic writer stores dsp cutoff 1.0 Hz; the diagnosis reads k from it (k=12 either way at 30 kHz)."""
    return None


def check_end_to_end(tmp: Path, c: Check) -> None:
    from filter_diag.run_all import run_diagnosis

    rng = np.random.default_rng(11)
    live_a = tmp / "instrument_only" / "live"
    dead_a = tmp / "instrument_only" / "dead"
    _make_session(live_a, "live", rng, tail=False)
    _make_session(dead_a, "dead", rng, tail=False)
    cfg = AnalysisConfig(bootstrap_n=100, min_trials=5)
    t0 = time.time()
    res = run_diagnosis(live=live_a, dead=dead_a, output_dir=tmp / "out_a", fast=True, quiet=True, cfg=cfg)
    print(f"  (instrument-only diagnosis in {time.time() - t0:.0f} s) {res.verdict[:160]}")
    ev = res.metadata["evidence"]
    c.ok(0.8 <= ev["tau_fit_ratio_to_dsp"] <= 1.2, f"instrument-only session: tau_fit/tau_dsp = {ev['tau_fit_ratio_to_dsp']:.2f}")
    c.ok(ev["same_sign_tail_fraction"] < 0.5, f"instrument-only session: opposite-sign tails dominate (same-sign {ev['same_sign_tail_fraction']:.0%})")
    c.ok(ev["recovery_collapses_after_removal"], f"instrument-only session: recovery collapses after filter removal (F1 {ev['F1_fraction_of_before']:.0%}, F2 {ev['F2_fraction_of_before']:.0%} of before)")
    c.ok(res.verdict.startswith("FILTER-DOMINATED"), f"instrument-only session verdict: {res.verdict.split(':')[0]}")
    c.ok(ev["live_dead_indistinguishable"] in (True, None), f"instrument-only session: live vs dead indistinguishable = {ev['live_dead_indistinguishable']}")
    c.ok({"fig1_tau_fit_distributions", "fig2_synthetic_vs_real_recovery", "fig3_synthetic_recovery_vs_amplitude", "fig4_live_vs_dead", "fig5_predicted_vs_observed", "fig6_example_epochs_filter_removed"} <= set(res.figures), f"all six figures produced ({len(res.figures)})")
    c.ok({"A_filter_settings_per_run", "B_tau_summary", "B_invariance_model", "C_synthetic_summary", "D_live_vs_dead", "E_decomposition_summary", "F_recovery_before_after"} <= set(res.tables), "all tables produced")

    live_b = tmp / "input_tail" / "live"
    _make_session(live_b, "live", rng, tail=True)
    res_b = run_diagnosis(live=live_b, dead=None, output_dir=tmp / "out_b", fast=True, quiet=True, cfg=cfg)
    ev_b = res_b.metadata["evidence"]
    print(f"  (input-tail diagnosis) {res_b.verdict[:160]}")
    c.ok(ev_b["same_sign_tail_fraction"] > 0.5, f"input-tail session: same-sign tails dominate ({ev_b['same_sign_tail_fraction']:.0%})")
    c.ok(not res_b.verdict.startswith("FILTER-DOMINATED"), f"input-tail session is not called filter-dominated: {res_b.verdict.split(':')[0]}")


def main() -> int:
    started = time.time()
    c = Check()
    with tempfile.TemporaryDirectory(prefix="filter_diag_selftest_") as tmpdir:
        tmp = Path(tmpdir)
        try:
            print("units"); check_units(c)
            print("end to end"); check_end_to_end(tmp, c)
        except AssertionError:
            print(f"\nSELFTEST FAILED after {c.n} checks")
            return 1
        except Exception:
            traceback.print_exc()
            print(f"\nSELFTEST ERROR after {c.n} checks")
            return 1
    print(f"\nall {c.n} checks passed in {time.time() - started:.1f} s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
